import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell } from "@/components/legal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms that govern your use of Rewrite Anything — accounts, acceptable use, AI output, billing, credits, and subscriptions.",
  alternates: { canonical: "/terms" },
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="July 2, 2026"
      lead={
        <>
          These terms are a binding agreement between you and Rewrite Anything (&ldquo;we,&rdquo;
          &ldquo;us&rdquo;) governing your use of <strong>rewrite-anything.com</strong> and its
          tools. By using the service, you agree to these terms. If you do not agree, please do not
          use the service.
        </>
      }
    >
      <h2>The service</h2>
      <p>
        Rewrite Anything is a collection of AI-powered tools that rewrite, summarize, and transform
        text you provide. Results are generated by a third-party AI model and returned to you. We may
        add, change, or remove tools and features at any time.
      </p>

      <h2>Eligibility and accounts</h2>
      <p>
        You must be at least 13 years old to use the service. You can use the free tier without an
        account; some features require signing in with your email. You are responsible for the
        activity that occurs under your account and for keeping access to your email secure. Provide
        accurate information and notify us of any unauthorized use.
      </p>

      <h2>Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Submit content you do not have the right to use, or that is unlawful.</li>
        <li>Use the service to create illegal, infringing, harassing, or harmful content.</li>
        <li>
          Attempt to bypass usage limits, the paywall, rate limiting, or any security or access
          controls.
        </li>
        <li>
          Scrape, resell, or build a competing service from our content, or abuse the service in a
          way that degrades it for others.
        </li>
        <li>Reverse engineer, disrupt, or overload the service or its infrastructure.</li>
      </ul>
      <p>We may suspend or terminate access for violations of these terms.</p>

      <h2>AI-generated output</h2>
      <p>
        Output is produced by an AI model and may be inaccurate, incomplete, or unsuitable for your
        purpose. <strong>You are responsible for reviewing and editing any output before you rely on
        or publish it.</strong> We do not warrant that output is accurate, original, or fit for any
        particular use, and it does not constitute legal, financial, medical, or other professional
        advice.
      </p>

      <h2>Content ownership</h2>
      <p>
        As between you and us, you retain your rights to the text you submit, and, to the extent
        permitted by law, we assign to you any rights we may have in the output generated for you.
        You are solely responsible for your input and for how you use the output. You grant us a
        limited license to process your input solely to provide the service. The Rewrite Anything
        name, logo, site, and software are our property and are protected by intellectual-property
        laws.
      </p>

      <h2>Free tier, credits, and subscriptions</h2>
      <ul>
        <li>
          <strong>Free tier:</strong> a limited number of free generations per day, shared across
          all tools, with no signup required.
        </li>
        <li>
          <strong>Credits:</strong> prepaid credit packs (one credit = one generation) that never
          expire and require a free account. Credit purchases are one-time and, except as required by
          law, are non-refundable once used.
        </li>
        <li>
          <strong>Subscriptions:</strong> unlimited plans that renew automatically each billing
          period until canceled, subject to reasonable fair-use limits to prevent abuse. You can
          cancel anytime from your account; cancellation takes effect at the end of the current
          period, and you keep access until then.
        </li>
      </ul>
      <p>
        Prices are shown on our{" "}
        <Link href="/pricing">pricing page</Link> and may change; changes will not affect the period
        you have already paid for. Payments are processed by Stripe, and by purchasing you also agree
        to Stripe&rsquo;s terms. Except where required by law, fees are non-refundable.
      </p>

      <h2>Termination</h2>
      <p>
        You may stop using the service at any time and delete your account. We may suspend or
        terminate your access if you violate these terms or if we discontinue the service. Sections
        that by their nature should survive termination — including ownership, disclaimers, and
        limitation of liability — will continue to apply.
      </p>

      <h2>Disclaimers</h2>
      <p>
        The service is provided <strong>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</strong>{" "}
        without warranties of any kind, whether express or implied, including merchantability, fitness
        for a particular purpose, and non-infringement. We do not warrant that the service will be
        uninterrupted, error-free, or secure.
      </p>

      <h2>Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, Rewrite Anything will not be liable for any indirect,
        incidental, special, consequential, or punitive damages, or any loss of data, revenue, or
        profits, arising from your use of the service. Our total liability for any claim relating to
        the service will not exceed the greater of the amount you paid us in the twelve months before
        the claim or USD $50.
      </p>

      <h2>Indemnification</h2>
      <p>
        You agree to indemnify and hold Rewrite Anything harmless from any claims, damages, and
        expenses arising from your content, your use of the service, or your violation of these terms.
      </p>

      <h2>Governing law</h2>
      <p>
        These terms are governed by the laws of the United States and the state in which we operate,
        without regard to conflict-of-laws rules. Any dispute will be resolved in the courts located
        there, unless applicable law requires otherwise.
      </p>

      <h2>Changes to these terms</h2>
      <p>
        We may update these terms from time to time. When we do, we will revise the &ldquo;Last
        updated&rdquo; date above. Your continued use of the service after changes take effect means
        you accept the updated terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Email us at{" "}
        <a href="mailto:support@rewrite-anything.com">support@rewrite-anything.com</a>.
      </p>
    </LegalShell>
  );
}
